MahlerFanSite/Controllers/ExtrasController.cs
using Microsoft.AspNetCore.Mvc;

namespace MahlerFanSite.Controllers
{
    public class ExtrasController : Controller
    {
        public IActionResult Index() => View();

        [HttpPost]
        public RedirectResult Index(string url) => Redirect(url);

        public BadRequestResult Bad() => BadRequest();

        public JsonResult Json()
        {
            // I am creating a dynamic object, similar to JavaScript's object
            dynamic json = new
            {
                UserId = 1,
                UserName = "John",
                Company = "Google",
                Salary = 500
            };
            return Json(json);
        }

        public string GetString() => "This is just a plain old boring string and nothing more!";
    }
}

MahlerFanSite/Controllers/SourcesController.cs
using System;
using System.Collections.Generic;
using MahlerFanSite.Models;
using Microsoft.AspNetCore.Mvc;

namespace MahlerFanSite.Controllers
{
    public class SourcesController : Controller
    {
        public SourcesController()
        {
            // Some books to fill our repository for testing
            if (BookRepository.Books.IsEmpty())
            {
                Book book = new Book
                {
                    BookId = 1,
                    Title = "Mahler Rocks!",
                    PublishedDate = new DateTime(2012, 6, 12)
                };
                BookRepository.AddBook(book);
                book = new Book
                {
                    BookId = 2,
                    Title = "Life of Mahler",
                    PublishedDate = new DateTime(2002, 6, 12)
                };
                BookRepository.AddBook(book);
                book = new Book
                {
                    BookId = 2,
                    Title = "Son of Mahler",
                    PublishedDate = new DateTime(2002, 6, 5)
                };
                BookRepository.AddBook(book);
            }

            // Some links to fill our repository for testing
            if (LinkRepository.Links.IsEmpty())
            {
                Link link = new Link
                {
                    LinkId = 1,
                    Description = "Wikipedia page about Mahler",
                    Url = "https://en.wikipedia.org/wiki/Gustav_Mahler"
                };
                LinkRepository.AddLink(link);
                link = new Link
                {
                    LinkId = 2,
                    Description = "Mahler's list of compositions",
                    Url = "https://en.wikipedia.org/wiki/List_of_compositions_by_Gustav_Mahler"
                };
                LinkRepository.AddLink(link);
                link = new Link
                {
                    LinkId = 3,
                    Description = "15 Facts",
                    Url = "https://www.classicfm.com/composers/mahler/pictures/mahlers-150th-birthday/"
                };
                LinkRepository.AddLink(link);
            }
        }
        
        public IActionResult Index() => View();

        public IActionResult Books()
        {
            List<Book> books = BookRepository.Books;

            // Books are now sorted alphabetically by the title
            books.Sort((a, b) => string.Compare(a.Title, b.Title, StringComparison.Ordinal));

            return View("Books", books);
        }

        public IActionResult Links()
        {
            List<Link> links = LinkRepository.Links;

            // Links are now sorted alphabetically by the description
            links.Sort((a, b) => string.Compare(a.Description, b.Description, StringComparison.Ordinal));

            return View("Links", links);
        }
        
        public IActionResult AddBook() => View();

        [HttpPost]
        public RedirectToActionResult AddBook(string title, string pubDate, string bookId)
        {
            Book book = new Book()
            {
                Title = title,
                PublishedDate = DateTime.Parse(pubDate),
                BookId = Int32.Parse(bookId)
            };
            BookRepository.AddBook(book);
            return RedirectToAction("Books");
        }
    }
}

MahlerFanSite/Views/Shared/_Form.cshtml
@{
    Layout = "_Layout";
}

<h1 class="display-5">Please enter the data below:-</h1>

<div class="my-shadow" style="background-color: #ffffdc; padding-top : 40px; padding-bottom: 40px; padding-left: 20px; padding-right: 20px; margin-top: 20px; margin-bottom: 40px">
    @RenderBody()
</div>

MahlerFanSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MahlerFanSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-yeti.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>

<div style="background-color: #ffffec">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary my-shadow">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mahler Fans</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="History">History</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Stories</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Stories">User Stories</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="AddStory">Add Story</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Sources</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="" asp-controller="Sources" asp-action="Index">Mahler Sources</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Sources" asp-action="Books">Book List</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Sources" asp-action="Links">Web Links</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="" asp-controller="Sources" asp-action="AddBook">Add Book</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Extras" asp-action="Index">Extras</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-top: 40px">
        <div class="jumbotron my-shadow" style="background-color: #dcffff; padding-top: 30px; padding-bottom: 20px">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="text-muted text-center" style="padding-bottom: 20px">
        <div class="container">
            <environment include="Development">
                &copy; 2019 Mahler Fans - @ViewBag.Title (Development Environment)
            </environment>
            <environment exclude="Development">
                &copy; 2019 Mahler Fans - @ViewBag.Title
            </environment>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</div>

</body>

</html>